### ISSUE TITLE
Fixing the docker image

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#48]
Issue is:

docker run -t -i -p 9443:9443 sirixdb/sirix
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: Connection refused
        ... 11 more
Dec 27, 2018 3:09:07 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: Connection refused
        ... 11 more

**Comment by JohannesLichtenberger** [comment]
The verticle wants to communicate with Keycloak on port 8080, but Keycloak is running within another docker container for instance.

**Comment by JohannesLichtenberger** [comment]
Seems to be Windows related, the --network=host option maybe because of the additional VM doesn't seem to work, same exception with `docker run -t -i -p 9443:9443 sirixdb/sirix`

**Comment by kmjayadeep** [comment]
Related to  #51. I cannot proceed with that unless docker file itself is fixed. So I'm looking into this.
According to the current dockerfile, the jar file must be built first before building the container. Shouldn't we doing this in the container itself, probably as a multi stage build?

**Comment by JohannesLichtenberger** [comment]
That would be great. However, I'm sadly no Docker expert. But I think the Dockerfile itself now works with Linux at least, thanks to another contribution.

And we should publish on Docker Hub again, I think. I don't remember why I disabled the automatic deployment images for SNAPSHOTs.

But if you can help with the multistage Docker image, that would be great. I think it was simply `mvn package` or something like that.
