### ISSUE TITLE
Large files to create resources / do not serialize the content

### ISSUE THREAD

**Issue by JohannesLichtenberger** [sirixdb/sirix#64]
Do not serialize the content if large files are going to be sent.

**Comment by RushikeshSawant** [comment]
Hi, I would like to work on this for Hacktoberfest. Can you please assign it to me?

**Comment by JohannesLichtenberger** [comment]
Thank you so much :-)

**Comment by JohannesLichtenberger** [comment]
Hey, still like to work on this?

Have a great weekend :+1:

**Comment by RushikeshSawant** [comment]
Hey @JohannesLichtenberger I have been trying to get the system up and running with `docker-compose up`. I managed to get fix `keycloak` URL issue by reading thru discussions in other issues threads. But now I am getting this error:
```
keycloak_1         | 15:34:04,831 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-1) JtaTransactionWrapper end
keycloak_1         | 15:34:06,012 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) new JtaTransactionWrapper
keycloak_1         | 15:34:06,012 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) was existing? false
keycloak_1         | 15:34:06,012 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper  commit
keycloak_1         | 15:34:06,012 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (Timer-2) JtaTransactionWrapper end
keycloak_1         | 15:34:06,013 DEBUG [org.keycloak.services.scheduled.ScheduledTaskRunner] (Timer-2) Executed scheduled task AbstractLastSessionRefreshStoreFactory$$Lambda$1149/0x000000084141f840
keycloak_1         | 15:34:08,058 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-1) new JtaTransactionWrapper
keycloak_1         | 15:34:08,058 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-1) was existing? false
keycloak_1         | 15:34:08,064 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-1) JtaTransactionWrapper rollback
server_1           | io.vertx.core.impl.NoStackTraceThrowable: Not Found: {"error":"Realm does not exist"}
server_1           | Oct 24, 2019 3:34:08 PM io.vertx.core.impl.ContextImpl
server_1           | SEVERE: Unhandled exception
server_1           | java.lang.IllegalStateException: Already resumed, but proposed with update Future{cause=Client is closed}
server_1           |    at kotlinx.coroutines.AbstractContinuation.resumeImpl(AbstractContinuation.kt:210)
server_1           |    at kotlinx.coroutines.AbstractContinuation.resumeWith(AbstractContinuation.kt:141)
server_1           |    at io.vertx.kotlin.coroutines.VertxCoroutineKt$awaitEvent$2$1.handle(VertxCoroutine.kt:67)
server_1           |    at io.vertx.ext.auth.oauth2.providers.KeycloakAuth.lambda$discover$0(KeycloakAuth.java:125)
server_1           |    at io.vertx.ext.auth.oauth2.providers.OpenIDConnectAuth.lambda$discover$1(OpenIDConnectAuth.java:44)
server_1           |    at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$null$0(OAuth2API.java:117)
server_1           |    at io.vertx.core.http.impl.HttpClientResponseImpl.handleException(HttpClientResponseImpl.java:267)
server_1           |    at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:254)
server_1           |    at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:493)
server_1           |    at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:194)
server_1           |    at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:652)
server_1           |    at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:602)
server_1           |    at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:560)
server_1           |    at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
server_1           |    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
server_1           |    at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
server_1           |    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
server_1           |    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
server_1           |    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
server_1           |    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
server_1           |    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
server_1           |    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
server_1           |    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
server_1           |    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
server_1           |    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
server_1           |    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
server_1           |    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
server_1           |    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
server_1           |    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
server_1           |    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
server_1           |    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
server_1           |    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
server_1           |    at java.base/java.lang.Thread.run(Thread.java:830)
server_1           |
server_1           | Oct 24, 2019 3:34:08 PM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
server_1           | SEVERE: Failed in deploying verticle
server_1           | io.vertx.core.impl.NoStackTraceThrowable: Not Found: {"error":"Realm does not exist"}
server_1           |
server_1           | io.vertx.core.impl.NoStackTraceThrowable: Not Found: {"error":"Realm does not exist"}
```

**Comment by JohannesLichtenberger** [comment]
Ah, I think you have to make sure that you create a new realm called "sirixdb". I've updated the [documentation](https://sirix.io/rest-api.html).

However, with docker-compose and `sudo docker-compose run --rm waitforkeycloak` I think the realm should hopefully be imported (worked for me always so far). And make sure that your branch is up-to-date. Let me know if that helps :-)

**Comment by JohannesLichtenberger** [comment]
A basic realm export file can be found here: https://github.com/sirixdb/sirix/blob/master/bundles/sirix-rest-api/src/test/resources/realm-export.json

**Comment by RushikeshSawant** [comment]
Thanks @JohannesLichtenberger 👍  I will give it a try over weekend. Cheers.

**Comment by JohannesLichtenberger** [comment]
@RushikeshSawant I would probably take it over if you have no time and I guess it was for #Hactoberfest? ;-)

**Comment by RushikeshSawant** [comment]
Hey @JohannesLichtenberger Sorry about this- got really caught up with other things.
Thanks for taking back on this one.
